name: Generate CloudFormation Template

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [closed]
  
  # Allow manual triggering
  workflow_dispatch:

# Add permissions block
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install Kodify CLI
        run: |
          dotnet tool install --global Kodify.CLI --version 0.0.1-dev-0005 || dotnet tool update --global Kodify.CLI --version 0.0.1-dev-0005

      - name: Check for existing template
        id: check_files
        run: |
          if [ -f "iac/template.yaml" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate CloudFormation template
        if: steps.check_files.outputs.exists == 'false'
        run: kodify cloudformation

      - name: Commit and push changes
        if: steps.check_files.outputs.exists == 'false'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add iac/
          git commit -m "chore: add cloudformation template [skip ci]"
          git push